common: &common
  adapter: postgresql
  username: traduco
  passord: tradpass
  host: localhost

development:
  <<: *common
  database: traduco_dev

test:
  <<: *common
  database: traduco_test

production:
  <<: *common
  database: traduco_prod
